//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shershunov_Practika2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DatePokaza { get; set; }
        public int Janorid { get; set; }
        public Nullable<int> PuskinCart { get; set; }
    
        public virtual Janor Janor { get; set; }
        public virtual PuskinCart PuskinCart1 { get; set; }
    }
}
